### ISSUE TITLE
Admin Login/Password

### ISSUE THREAD

**Issue by thecloudgarage** [michaelkerr0576/rellygudfutos#6]
I have setup the site on my ec2 instance., but am clueless to what is the default admin user id and password. Do you need to initialize that in the mongodb database., if so, kindly suggest.

**Comment by michaelkerr0576** [comment]
The code to create a user is commented out. I initially created an admin using Postman with this code. Then I commented it out, bit of a hack but I wanted the password to be hashed and secure on MongoDB. I recommend you do the same and uncomment out this code and create all the users you would like. Delete users is also commented out. You can create some frontend elements to use these if you like.

See the routes for users @ 
[routes/users](https://github.com/michaelkerr0576/rellygudfutos/blob/master/server/api/routes/users.js)

// Only admin can create other uses   // @route   POST /users/
// @desc    Posts user
// @access  Private
// router.post("/create",   UsersController.users_create);

See the controller for users @ 
[controllers/users](https://github.com/michaelkerr0576/rellygudfutos/blob/master/server/api/controllers/users.js)

// exports.users_create = async (req, res, next) => {   //   await   User.find({ email: req.body.email })
//     .exec()
//       .then(user => {
//       if   (user.length >= 1) {
//         //0   creates new user, 1 already exists
//           return res.status(409).json({
//             message: "Email already exists"
//         });
//       }   else {
//         bcrypt.hash(req.body.password,   10, (err, hash) => {
//             //10 adds string salting so hash cant be looked up in dictionary tables
//             if (err) {
//               return res.status(500).json({
//                 error: err //could not safely store password
//               });
//             } else {
//               const user = new User({
//                 _id: new mongoose.Types.ObjectId(),
//                 email: req.body.email,
//                 password: hash
//               });
//               user
//                 .save()
//                 .then(result => {
//                   console.log(result);
//                   res.status(201).json({
//                     message: "User Created"
//                   });
//               })
//                 .catch(err => {
//                   console.log(err);
//                   res.status(500).json({ error: err });
//                 });
//           }
//         });
//       }
//     });
// };

And a word of warning, there is also an issue where a photo does not include metadata that it fails to upload. Currently only photos with the below information can be uploaded. I would add code to handle where these values are not populated.

![image_metadata](https://user-images.githubusercontent.com/53580213/92127103-e18ce100-edf8-11ea-96c1-40f74a97a7da.png)

**Comment by thecloudgarage** [comment]
Thanks a bunch.
